### ISSUE TITLE
File to import not found or unreadable: flint.

### ISSUE THREAD

**Issue by robd** [ezekg/flint#37] opened 2015-09-23 16:37 UTC
I'm probably doing something stupid, but I'm trying to get flint up and running with a rails 3 project and I'm seeing this error when I call `@import "flint";`:

`File to import not found or unreadable: flint.`

I've included `flint-gs` in my gemfile and installed it. Does flint gs work with rails? Are there any other steps needed to get this working?

**Comment by ezekg** [comment] 2015-09-23 16:54
It should work fine with Rails. Could you post your Gemfile and any relevant lines from the Sass file that you're importing Flint into (are you doing any requires from within that file via Sprockets)?

**Comment by ezekg** [comment] 2015-09-25 18:38
@robd did you get this resolved?

**Comment by robd** [comment] 2015-09-25 19:36
Hey @ezekg. Sorry - I didn't get a chance to dig into this yet, but it's useful knowing it should work with rails. I'm using sprockets, but not compass. I'm using a lot of other gems and quite old versions of things. I will try to get a minimal setup with the failure and come back with more info when I have time.

**Comment by ezekg** [comment] 2015-09-25 20:14
Okay, sounds good.

**Comment by robd** [comment] 2015-11-20 20:15
@ezekg I tried to debug sass a bit and found that the ENV['SASS_PATH'] wasn't set in the [sass load_paths method](https://github.com/sass/sass/blob/2364f526d01602c58b93b3f2cc342a19d8839910/lib/sass.rb#L38). Therefore, I added debug to see what was going on in [flint.rb](https://github.com/ezekg/flint/blob/f7b92435159044945bc1f40e0dd28f955efec614/lib/flint.rb#L17) and found that my flint.rb wasn't being called at all. I have checked that I only have one version of flint installed. So it looks like maybe a problem with my bundler setup (I'm using bundler 1.9.4), but I can't really understand what the problem is. 

I realise that this is quite vague, but can you think of anything I should check? If not I will try to set up a new test project without any other gems and see if I can get that to work. Thanks

**Comment by ezekg** [comment] 2015-11-20 21:56
I recently adjusted the way the load path is set up. Could you try updating Flint to the latest version and let me know if the issue is resolved? Do you know how other Sass libraries handle Rails integration? Trying to figure out if I might just be missing a step that Rails requires.

**Comment by robd** [comment] 2015-11-20 22:18
I saw that you have recently updated things. I'm running flint version 2.3.6 from the gem, but I don't see a record of this in github (ie no release / tag) (was this an unintentional release?). I will try with flint from github master.

**Comment by robd** [comment] 2015-11-20 22:43
OK, I made progress here. Upgrading to the latest flint didn't help, but I was able to get bundler to load the gem using the require option:

```ruby
# Gemfile
gem 'flint-gs', :github => 'ezekg/flint', :branch => 'master', :require => 'flint'
```

I'm not sure why bundler didn't load flint.rb automatically. I think maybe it is because the gem name has a hyphen in it and this causes some sort of special behaviour - http://guides.rubygems.org/rubygems-basics/#requiring-code

> Drop Ruby code into lib, name a Ruby file the same as your gem (for the gem “freewill” the file should be freewill.rb, see also [name your gem](http://guides.rubygems.org/name-your-gem/)) and it’s loadable by RubyGems.

Maybe the main file has to be called flint-gs.rb?

**Comment by ezekg** [comment] 2015-11-20 23:49
You're right, I had to namespace Flint with `-gs` because it was already taken as a Gem name. I figured that would become an issue later on down the road, but I can't change it in a backwards compatible way currently. Maybe when v3 rolls around I can get that fixed up.

For now, your solution works well, correct? Would you mind making a pull request and adding a line in the readme for Rails usage? You're probably more well versed than I am.

**Comment by ezekg** [comment] 2015-11-21 03:53
I think if I added a file named `flint-gs.rb` alongside (and that requires) `flint.rb`, it would probably fix the issue until it can be fully resolved in the next major release. I will look into doing that tomorrow. Thanks again for the report and solution!

**Comment by robd** [comment] 2015-11-21 11:41
I tried hacking a `flint-gs.rb` file alongside `flint.rb` as suggested in my checked out gem and this seemed to work OK and allow me to remove the `:require => 'flint'` option :+1:

Since you're adding this very soon, I'm assuming there is now no need to update the readme. I'm happy to test once you've made the the change if that would be helpful.

**Comment by ezekg** [comment] 2015-11-21 15:59
Great to hear. Can you try updating to `2.3.7` and let me know if the issue is resolved? And your correct, if this fixes the issue when the readme doesn't need to be updated. :+1:

**Closed** 2015-11-26 19:40 UTC

**Comment by robd** [comment] 2015-12-01 20:17
Confirmed that 2.3.7 works for me - thanks for the fix.

**Comment by ezekg** [comment] 2015-12-01 21:18
Awesome :+1: no problem.
